[package]
name = "day03b"
version = "0.1.0"
authors = ["Dominic Dagradi <ddagradi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
